### https://taskfile.dev
###---------------------

version: '2'

vars:
  VERSION: 0.0.0
  PLUGIN: armen.utopie
  BUILTAT:
    sh: date +%s
  LDFLAGS: -X 'main._version={{.VERSION}}' -X 'main._builtAt={{.BUILTAT}}'

tasks:
  static:
    cmds:
      - go generate -tags devel data/static.go

  lint:
    cmds:
      - golangci-lint run

  test:
    cmds:
      - go test -cover -v ./...

  build:
    cmds:
      - go build -buildmode=plugin -ldflags "{{.LDFLAGS}}" -o $GOPATH/bin/{{.PLUGIN}}.so ./plugin/main.go

  default:
    cmds:
      - task: static
      - task: lint
      - task: test
      - task: build

  devel_lint:
    cmds:
      - golangci-lint run --build-tags devel

  devel_test:
    cmds:
      - go test -tags=devel -cover -v ./...

  devel_build:
    cmds:
      - go build -tags=devel -buildmode=plugin -ldflags "{{.LDFLAGS}}" -o $GOPATH/bin/{{.PLUGIN}}.so ./plugin/main.go

  devel:
    cmds:
      - task: devel_lint
      - task: devel_test
      - task: devel_build
